name: 'Datapoint Producer'
description: 'Add datapoint at metrics db'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
inputs:
  influxdb-token:
    description: 'token to access influxdb instance'
    require: true
  influxdb-measurement:
    description: 'influxdb measurement, used as metrics aggragetor'
    require: false
    default: 'deployment'
  influxdb-url:
    description: 'url to influxdb instance'
    require: true
  influxdb-org:
    description: 'organizarion used by influxdb'
    require: false
    default: 'Contraktor'
  app:
    description: 'application that was affected'
    require: true

runs:
  using: 'composite'
  steps:
    - name: make sure that python is installed
      if: |
        !contains(runner.name, 'docker-runner')
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/src/require.txt

    - name: send datapoint to metrics db
      shell: bash
      run: |
        export INFLUX_TOKEN=${{ inputs.influxdb-token }}
        export INFLUX_MEASUREMENT=${{ inputs.influxdb-measurement }}
        export INFLUX_URL=${{ inputs.influxdb-url }}
        export INFLUX_ORG=${{ inputs.influxdb-org }}
        export APP=${{ inputs.app }}
        python ${{ github.action_path }}/src/main.py
