name: 'Datapoint Producer'
description: 'Add datapoint at metrics db'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
inputs:
  influxdb-bucket:
    description: 'influxdb bucket, used as metrics aggragetor'
    require: false
    default: 'deployment'
  influxdb-org:
    description: 'organizarion used by influxdb'
    require: false
    default: 'Contraktor'
  app:
    description: 'application that was affected'
    require: true

runs:
  using: 'composite'
  steps:
    - name: make sure that python is installed
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/src/require.txt

    - name: send datapoint to metrics db
      shell: bash
      run: |
        export INFLUX_TOKEN=${{ secrets.INFLUXDB_TOKEN }}
        export INFLUX_URL=${{ secrets.INFLUXDB_URL }}
        export INFLUX_BUCKET=${{ inputs.influxdb-buck }}
        export INFLUX_ORG=${{ inputs.influxdb-org }}
        export APP=${{ inputs.app }}
        python ${{ github.action_path }}/src/main.py
